### ISSUE TITLE
Broken download link on main page 

### ISSUE THREAD

**Issue by GimmickyApps** [ACRA/acra.github.com#2]
http://search.maven.org/remotecontent?filepath=ch/acra/acra/4.7.01/acra-4.7.0.zip doesn't exist

Also should it be 4.8.1 for that and the .jar link now?

**Comment by william-ferguson-au** [comment]
Can you provide a more specific page link.
The link above is a generated link  from Maven Central.

**Comment by GimmickyApps** [comment]
That's what is there in the root index.html quick start guide already...what it should be I don't know, I'm new here :). Just thought I should report the broken link 

-----Original Message-----

**Comment by william-ferguson-au** [comment]
Ah, OK. I didn't realise that Kevin had burned the version into www.acra.ch
That should be better now.
